# -*- coding: utf-8 -*-
"""Copy of TASK-1.ipynb file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kw_VugrWqaZgEY6knk4tFba_iX04lXdu
"""

# 1. User Login Check

#step 1:store predefined credentials
stored_credentials={
    "admin":"1234"
}

#step 2:Take input from user
entered_username=input("Enter Username:").strip()
entered_password=input("Enter Password:").strip()

#step 3:Validate login using dictionary lookup
if stored_credentials.get(entered_username) == entered_password:
  print("Login Successful")
else:
  print("Invalid Credentials")

#2.PASS FAIL ANALYZER

# Step 1: Store Marks
marks = [45, 78, 90, 33, 60]

# Step 2: Initialize Counters
pass_count = 0
fail_count = 0

# Step 3: Analyze Marks
for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1

# Step 4: Display Results
print("========== STUDENT RESULT REPORT ==========")
print("Passing Criteria : Marks >= 50")
print("Marks List       :", marks)
print("-------------------------------------------")
print("Total Students   :", len(marks))
print("Students Passed  :", pass_count)
print("Students Failed  :", fail_count)
print("-------------------------------------------")

if fail_count == 0:
    print("Overall Result   : All Students Passed")
elif pass_count == 0:
    print("Overall Result   : All Students Failed")
else:
    print("Overall Result   : Mixed Results (Pass & Fail)")

print("===========================================")

#3. Simple Data Cleaner

#step 1: Original Data
names=["Alice","bob","CHARLIE"]

#step 2:Initialize cleaned list
cleaned_names=[]

#step 3:Clean each name
for name in names:
  cleaned_name=name.strip().lower()
  cleaned_names.append(cleaned_name)

#step 4:Display Output
print("-----Data Cleaning Report-----")
print("Original List:",names)
print("After Removing Spaces & Converting to Lowercase")
print("Cleaned List :",cleaned_names)
print("-------------------------")

#4. Message Length Analyzer

# step 1:Original Messages
messages = ["Hi","Welcome to the platform","OK"]

print("-----Message Length Report-----")

#step 2:Analyze each message
for msg in messages:
  length = len(msg)
  print("Message:",msg)
  print("Length:",length)

#step 3:Flag long messages
if length >10:
  print("Status :Long Message(More than 10 characters)")
else:
  print("status :Short Messages")
  print("-----------------------------")
  print("Analysis Completed")

# 5.Error Message Detector

def detect_errors(logs):
    # Count ERROR messages
    error_count = logs.count("ERROR")
    # Print total error count
    print("Total number of ERROR entries:", error_count)
# Given system logs
logs = ["INFO", "ERROR", "WARNING", "ERROR"]
# Function call
detect_errors(logs)