# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/riyadharavath4-stack/f5eb78c17ee8116e99980eea2d723e7f/copy-of-untitled2.ipynb
"""

# 1.Program:Unique words in a sentence

#Taking input from user
sentence = input("Enter sentence:")
#split the sentence into words
words = sentence.split()
#convert list to set to remove duplicates
unique_words = set(words)
#display results
print("Unique words count:",len(unique_words))
print("Unique words:",unique_words)

2.#Highest Salary from Employee Data

#creating dictionary of employees and salaries
employees = {
    "Ravi":75000,
    "Anita":68000,
    "Kiran":72000,
}
#find employee with highest salary
highest_employee = max(employees,key=employees.get)
highest_salary = employees[highest_employee]
#display result
print("Highest Salary:",highest_employee,"-",highest_salary)

# 3.Find Maximum and Minimum Values

#given list
numbers = [45,22,89,10,66]

#Intialize max and min with first element
maximum = numbers[0]
minimum = numbers[0]

#loop through the list
for num in numbers:
  if num>maximum:
    maximum = num
    if num<minimum:
      minimum=num
#display results
print("List:",numbers)
print("max:",maximum)
print("min:",minimum)

4.#Count Products Above a Price Threshold

prices =[450,1200,899,1500,300]

count = 0

#loop through each price
for price in prices:
  if price>1000:
    count +=1
print("Products above 1000:",count)

#5.Calculate Attendance Percentage

attendance = ["P","P","A","P","P"]

present_count = attendance.count("P")
total_days=len(attendance)

attendance_percentage = (present_count/total_days)*100

print(attendance_percentage)